return {
	"nvim-lua/plenary.nvim", -- lua functions that many plugins use
	"christoomey/vim-tmux-navigator", -- tmux & split window navigation
	"williamboman/mason.nvim",
	"williamboman/mason-lspconfig.nvim",
	"neovim/nvim-lspconfig",
	"mfussenegger/nvim-lint",
	-- "airblade/vim-gitgutter",
	-- "github/copilot.vim",
	"ellisonleao/gruvbox.nvim",
	"nvim-lua/plenary.nvim",
	"theRealCarneiro/hyprland-vim-syntax",
	"echasnovski/mini.icons",
	"nvim-telescope/telescope-fzf-native.nvim",
	-- colorschemes
	"shaunsingh/nord.nvim",
	"marko-cerovac/material.nvim",
	"NLKNguyen/papercolor-theme",
	"ayu-theme/ayu-vim",
	"projekt0n/github-nvim-theme",
	"ishan9299/nvim-solarized-lua",
	"rose-pine/neovim",
	"sainnhe/gruvbox-material",
	"sainnhe/sonokai",
	"tiagovla/tokyodark.nvim",
	"navarasu/onedark.nvim",
	"bluz71/vim-moonfly-colors",
	"projekt0n/github-nvim-theme",
	"projekt0n/github-nvim-theme",
	"projekt0n/github-nvim-theme",
	"habamax/vim-habamax",
	"elkowar/yuck.vim",
}
