working_directory = "/home/blackgaze"

import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/challenger_deep.toml"
]

[font]
size = 10.0

[window]
dimensions = { columns = 91, lines = 24 }
opacity = 0.5
# blur = true     --works only on wayland

[colors]
transparent_background_colors = true
